// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  hasSupabaseConfig,
  missingSupabaseEnvVars,
  SUPABASE_KEY_SOURCE,
  SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_URL,
  SUPABASE_URL_SOURCE,
} from './env';

if (!hasSupabaseConfig) {
  const missing = missingSupabaseEnvVars().join(', ');
  console.error('CRITICAL: Supabase environment variables not loaded.');
  console.error(`Missing: ${missing}`);
  console.error(
    'Set VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY, or VITE_SUPABASE_PROJECT_ID + VITE_SUPABASE_ANON_KEY.'
  );
} else {
  console.log('Supabase configuration loaded');
  console.log(`URL source: ${SUPABASE_URL_SOURCE}`);
  console.log(`Key source: ${SUPABASE_KEY_SOURCE}`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
const fallbackUrl = 'https://invalid.supabase.co';
const fallbackKey = 'invalid-anon-key';

export const supabase = createClient<Database>(SUPABASE_URL || fallbackUrl, SUPABASE_PUBLISHABLE_KEY || fallbackKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
