name: Deploy to Vercel

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel Production
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_3CBWeLCoBzCs94lgGeIyDm1i
          VERCEL_PROJECT_ID: prj_XzscP3mcJ7i4RKEyQpUaR9uMEe4V
